version: "3"

services:
  app:
    build:
      context: ./docker
      dockerfile: app.dockerfile
      args:
        WITH_XDEBUG: "true"
    working_dir: /var/www
    volumes:
      - ./:/var/www:cached
      - ./docker/config/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - ./docker/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
    expose:
      - "9000"

  web:
    image: nginx:latest
    working_dir: /var/www
    volumes:
      - ./:/var/www:cached
      - ./docker/config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    restart: always
    depends_on:
      - app
      - database

  database:
    image: mysql:5.7
    restart: always
    volumes:
      - ./docker/.db:/var/lib/mysql:cached
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "33061:3306"